In [1]:
import numpy as np

# Create a 1-D array with 5 elements
arr = np.array([10, 20, 30, 40, 50])

print("Original array:", arr)

# a) Add 2 to all elements
print("After adding 2:", arr + 2)

# b) Multiply all elements by 3
print("After multiplying by 3:", arr * 3)

# c) Divide every element by 2
print("After dividing by 2:", arr / 2)

Original array: [10 20 30 40 50]
After adding 2: [12 22 32 42 52]
After multiplying by 3: [ 30  60  90 120 150]
After dividing by 2: [ 5. 10. 15. 20. 25.]


# ques2

In [2]:
arr = np.array([1, 2, 3, 6, 4, 5])

In [3]:
import numpy as np

arr = np.array([1, 2, 3, 6, 4, 5])

reverse = arr[::-1]

print("Original array:", arr)
print("Reversed array:", reverse)

Original array: [1 2 3 6 4 5]
Reversed array: [5 4 6 3 2 1]


In [4]:
x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])

In [5]:
import numpy as np

x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])

values, counts = np.unique(x, return_counts=True)

max_count = np.max(counts)

most_frequent = values[counts == max_count]

print("Most frequent value:", most_frequent)
print("Frequency:", max_count)

for value in most_frequent:
    indices = np.where(x == value)[0]
    print("Indices:", indices)

Most frequent value: [1]
Frequency: 5
Indices: [0 5 7 8 9]


In [6]:
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])


In [7]:
import numpy as np

y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])

values, counts = np.unique(y, return_counts=True)

max_count = np.max(counts)

most_frequent = values[counts == max_count]

print("Most frequent values:", most_frequent)
print("Frequency:", max_count)

for value in most_frequent:
    indices = np.where(y == value)[0]
    print("Value", value, "indices:", indices)

Most frequent values: [1 3]
Frequency: 3
Value 1 indices: [0 1 2]
Value 3 indices: [4 8 9]


# ques 3


In [8]:
import numpy as np

arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

In [9]:


# a) 1st row, 2nd column
print("1st row, 2nd column:", arr[0, 1])

# b) 3rd row, 1st column
print("3rd row, 1st column:", arr[2, 0])

1st row, 2nd column: 20
3rd row, 1st column: 70


# ques 4

In [11]:
import numpy as np

# Create 25 evenly spaced numbers from 10 to 100
arr = np.linspace(10, 100, 25)

print("Original array:")
print(arr)

# Dimensions
print("Shape:", arr.shape)

# Total number of elements
print("Total elements:", arr.size)

# Data type
print("Data type:", arr.dtype)

# Total bytes
print("Total bytes:", arr.nbytes)

# Reshape
reshaped = arr.reshape(5, 5)

print("\nReshaped array (5 x 5):")
print(reshaped)

# Using T
column = arr.reshape(25, 1)

print("\nColumn array:")
print(column)

print("\nTranspose using T:")
print(column.T)

print("Shape after transpose:", column.T.shape)

Original array:
[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Shape: (25,)
Total elements: 25
Data type: float64
Total bytes: 200

Reshaped array (5 x 5):
[[ 10.    13.75  17.5   21.25  25.  ]
 [ 28.75  32.5   36.25  40.    43.75]
 [ 47.5   51.25  55.    58.75  62.5 ]
 [ 66.25  70.    73.75  77.5   81.25]
 [ 85.    88.75  92.5   96.25 100.  ]]

Column array:
[[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]

Transpose using T:
[[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
   47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
   85.    88.75  92.5   96.25 100.  ]]
Shape after transpose: (1, 25)


# ques 5

In [13]:
import numpy as np

ucs420_maansi = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 100, 110, 120]
])

print(ucs420_maansi)

[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]


In [14]:
print("Mean:", np.mean(ucs420_maansi))

Mean: 65.0


In [15]:
print("Median:", np.median(ucs420_maansi))

Median: 65.0


In [16]:
print("Median:", np.median(ucs420_maansi))

Median: 65.0


In [17]:
print("Maximum:", np.max(ucs420_maansi))

Maximum: 120


In [18]:
print("Minimum:", np.min(ucs420_maansi))

Minimum: 10


In [19]:
# Reshape to 4 x 3
reshaped_ucs420_maansi = ucs420_maansi.reshape(4, 3)

print("\nReshaped array (4 x 3):")
print(reshaped_ucs420_maansi)

# Resize to 2 x 3
resized_ucs420_maansi = np.resize(ucs420_maansi, (2, 3))

print("\nResized array (2 x 3):")
print(resized_ucs420_maansi)


Reshaped array (4 x 3):
[[ 10  20  30]
 [ 40  50  60]
 [ 70  80  90]
 [100 110 120]]

Resized array (2 x 3):
[[10 20 30]
 [40 50 60]]
