In [1]:
import numpy as np

# Sensor readings
temperature = np.array([25, 28, 31, 35, 38, 27, 33, 40])

# a) Add +2°C measurement error to every reading
corrected_temperature = temperature + 2

print("Original temperatures:", temperature)
print("Corrected temperatures:", corrected_temperature)


# b) Convert Celsius to Fahrenheit
fahrenheit = (9/5) * corrected_temperature + 32

print("Temperature in Fahrenheit:", fahrenheit)


# c) Identify readings greater than 32°C
readings_above_32 = corrected_temperature[corrected_temperature > 32]

print("Readings greater than 32°C:", readings_above_32)


# d) Count how many readings exceed 32°C
count = np.sum(corrected_temperature > 32)

print("Number of readings exceeding 32°C:", count)

Original temperatures: [25 28 31 35 38 27 33 40]
Corrected temperatures: [27 30 33 37 40 29 35 42]
Temperature in Fahrenheit: [ 80.6  86.   91.4  98.6 104.   84.2  95.  107.6]
Readings greater than 32°C: [33 37 40 35 42]
Number of readings exceeding 32°C: 5


# ques2


In [2]:
import numpy as np

steps = np.array([
    [5000, 6200, 7100],
    [8000, 7500, 9000],
    [4500, 5100, 4800],
    [9000, 8500, 9500]
])

In [3]:
total = np.sum(steps)
print(total)

84200


In [4]:
mean = np.mean(steps)
print(mean)

7016.666666666667


In [5]:
print(np.max(steps))

9500


In [6]:
print(np.min(steps))

4500


In [7]:
np.sum(steps, axis=0)

array([26500, 27300, 30400])

In [8]:
daily_total = np.sum(steps, axis=0)

print(daily_total)



[26500 27300 30400]


In [9]:
np.sum(steps, axis=1)

array([18300, 24500, 14400, 27000])

In [11]:
position = np.argmax(steps)
print(position)


11


In [12]:
position = np.unravel_index(np.argmax(steps), steps.shape)

print(position)



(np.int64(3), np.int64(2))


# ques2

In [13]:
import numpy as np

steps = np.array([
    [5000, 6200, 7100],
    [8000, 7500, 9000],
    [4500, 5100, 4800],
    [9000, 8500, 9500]
])

# a) Total steps
print("Total steps:", np.sum(steps))

# b) Mean
print("Mean steps:", np.mean(steps))

# c) Maximum and minimum
print("Maximum:", np.max(steps))
print("Minimum:", np.min(steps))

# d) Total for each day
print("Total for each day:", np.sum(steps, axis=0))

# e) Total for each user
print("Total for each user:", np.sum(steps, axis=1))

# f) Position of maximum
position = np.unravel_index(np.argmax(steps), steps.shape)

print("Position of maximum:", position)
print("Maximum steps:", steps[position])

Total steps: 84200
Mean steps: 7016.666666666667
Maximum: 9500
Minimum: 4500
Total for each day: [26500 27300 30400]
Total for each user: [18300 24500 14400 27000]
Position of maximum: (np.int64(3), np.int64(2))
Maximum steps: 9500


# ques3

In [14]:
original = np.array([1, 2, 3, 4, 5, 6])

In [16]:
import numpy as np

original = np.array([1, 2, 3, 4, 5, 6])

print(original)

[1 2 3 4 5 6]


In [19]:
subset = original[1:5]

print(subset)

[2 3 4 5]


In [20]:
subset[0] = 999

print("Original:", original)
print("Subset:", subset)

Original: [  1 999   3   4   5   6]
Subset: [999   3   4   5]


In [21]:
copied = original[1:5].copy()

In [22]:
print("Original:", original)
print("Copied:", copied)

Original: [  1 999   3   4   5   6]
Copied: [999   3   4   5]


In [23]:
np.arange(1, 13)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [25]:
matrix = np.arange(1, 13).reshape(3, 4)

In [26]:
first_row = matrix[0, :]
print(first_row)

[1 2 3 4]


In [27]:
last_row = matrix[-1, :]
print(last_row)

[ 9 10 11 12]


In [28]:
second_column = matrix[:, 1]
print(second_column)

[ 2  6 10]


In [29]:
subset_matrix = matrix[0:2, 1:3]

print(subset_matrix)

[[2 3]
 [6 7]]


In [30]:
flat1 = matrix.flatten()

print("Using flatten():", flat1)

Using flatten(): [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [31]:
flat2 = matrix.ravel()

print("Using ravel():", flat2)

Using ravel(): [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [32]:
ravel_array = matrix.ravel()

In [33]:
ravel_array[0] = 100

In [35]:
print("Ravel:", ravel_array)
print("Original matrix:")
print(matrix)

Ravel: [100   2   3   4   5   6   7   8   9  10  11  12]
Original matrix:
[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [36]:
flat_array = matrix.flatten()

flat_array[0] = 500

print("Flattened:", flat_array)
print("Original matrix:")
print(matrix)

Flattened: [500   2   3   4   5   6   7   8   9  10  11  12]
Original matrix:
[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [37]:
r = matrix.ravel()
r[0] = 100

In [38]:
f = matrix.flatten()
f[0] = 500


In [39]:
print("Shape:", matrix.shape)
print("Dimensions:", matrix.ndim)
print("Size:", matrix.size)
print("Data type:", matrix.dtype)

Shape: (3, 4)
Dimensions: 2
Size: 12
Data type: int64


# ques4

In [40]:
import numpy as np

X = np.array([
    [6, 70, 3],
    [5, 50, 6],
    [8, 80, 2],
    [4, 30, 8]
])

y = np.array([40, 65, 30, 85])

In [42]:
print("Shape:", X.shape)
print("Dimensions:", X.ndim)

Shape: (4, 3)
Dimensions: 2


In [43]:
XT = X.T

print("X.T:")
print(XT)

X.T:
[[ 6  5  8  4]
 [70 50 80 30]
 [ 3  6  2  8]]


In [44]:
XTX = X.T @ X

print("X.T @ X:")
print(XTX)

X.T @ X:
[[  141  1430    96]
 [ 1430 14700   910]
 [   96   910   113]]


In [45]:
XTX_inv = np.linalg.inv(XTX)

print("Inverse:")
print(XTX_inv)

Inverse:
[[ 1.10521428 -0.09848746 -0.14581398]
 [-0.09848746  0.00891203  0.01190129]
 [-0.14581398  0.01190129  0.0368847 ]]


In [46]:
XTX = X.T @ X
XTX_inv = np.linalg.inv(XTX)
XTy = X.T @ y

beta = XTX_inv @ XTy

print("Beta:", beta)

Beta: [-0.15921454  0.14083853 10.06302242]


In [47]:

# f) Coefficients
print("\nCoefficient for Sleep:", beta[0])
print("Coefficient for Activity:", beta[1])
print("Coefficient for Stress:", beta[2])


# g) Prediction
new_user = np.array([5, 40, 7], dtype=float)

predicted_score = new_user @ beta

print("\nNew user:", new_user)
print("Predicted assistance score:", predicted_score)



Coefficient for Sleep: -0.15921454159470666
Coefficient for Activity: 0.14083852991905693
Coefficient for Stress: 10.06302242271459

New user: [ 5. 40.  7.]
Predicted assistance score: 75.27862544779087
